# Default values for nexus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

environment: test

strategy:
  type: Recreate
restartPolicy: Always

readinessPath: '/@molgenis-ui/legacy-lib/dist/context.css'

image:
  repository: registry.hub.docker.com
  name: molgenis/molgenis-frontend
  tag: latest
  pullPolicy: Always

service:
  name: molgenis-frontend
  type: ClusterIP
  port: 80

proxy:
  backend:
    override: true
    service:
      enabled: true
  frontend: 
    override: true
    #
    # If you want to connect inside the same cluster you can specify the targetNamespace and targetRelease.
    # This way the service will be resolved inside the cluster.
    #
    #      targetNamespace:
    #      targetRelease:

    # When you connect to an external MOLGENIS backend you can set proxy.backend.service.enabled=false and specify the backend url.
    #
    #    url: https://master.dev.molgenis.org


    #
    # You can define custom urls you want to proxy on a certain path.
    # This needs to be done in the values.yaml at this moment. In the questions.yaml you can specify only 1.
    # You can specify whether you use unpkg.com or not. When you use unpgk.com the redirect target will be
    # used to resolve the right version.
    #
    #  custom:
    #  - url: https://my-app
    #    path: my-app
    #    unpkg: true

    custom:
    - url: https://unpkg.com/@mswertz
      path: "@mswertz"
      unpkg: true

    #
    # You can define urls in the @molgenis-experimental namespace you want to proxy on a certain path.
    # This needs to be done in the values.yaml at this moment. In the questions.yaml you can specify only 1.
    # You can specify whether you use unpkg.com or not. When you use unpgk.com the redirect target will be
    # used to resolve the right version.
    #
    #  experimental:
    #  - url: https://unpkg.com/@molgenis-experimental/app-name@x.x.x/
    #    path: @molgenis-experimental
    #    unpkg: true

    experimental:
    - url: https://unpkg.com/@molgenis-experimental
      path: "@molgenis-experimental"
      unpkg: true

ingress:
  enabled: true
  path: /
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 0
  basicAuth:
    enabled: false
    realm: "Authentication Required"
    auth: "xxxx"

resources: {}

nodeSelector:
  deployPod: "true"

tolerations: []

affinity: {}
