apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-cleanup
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          {{- with $.Values.cleanup }}
          - name: cleanup
            image: {{ .image.repository }}/{{ .image.name }}:{{ .image.tag }}
            command: ["/bin/sh","-c"]
            args: ["rancher context switch {{ .project }}; \
                    rancher app | awk '{print $2}' | grep preview- > preview.list; \
                    xargs rancher app delete < preview.list"]
            volumeMounts:
            - name: rancher-config
              mountPath: ~/.rancher
            env:
              
          volumes:
          - name: rancher-config
            secrete:
              secret-name: cli2-json
          restartPolicy: OnFailure
          {{- end }}
        
        
