apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: {{ .Values.nexus.name }}
  labels:
    app: {{ .Values.nexus.name }}
    environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.nexus.strategy.type }}
  selector:
    matchLabels:
      app: {{ .Values.nexus.selector }}
  template:
    metadata:
      labels:
        app: {{ .Values.nexus.name }}
      creationTimestamp: null
    spec:
      restartPolicy: {{ .Values.nexus.restartPolicy }}
      initContainers:
      - name: nexus-nfs
        image: busybox
        command: ["sh", "-c", "chown -R 200:200 /nexus-data"]
        volumeMounts:
        - name: molgenis-nexus-nfs
          mountPath: "/nexus-data"
      containers:
      - name: {{ .Values.nexus.name }}
        image: "{{ .Values.nexus.image.repository }}:{{ .Values.nexus.image.tag }}"
        imagePullPolicy: {{ .Values.nexus.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.nexus.port.ui }}
        - containerPort: {{ .Values.nexus.port.docker }}
        volumeMounts:
        - name: molgenis-nexus-nfs
          mountPath: /nexus-data
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.nexus.port.ui }}
          initialDelaySeconds: 120
          periodSeconds: 20
          failureThreshold: 15
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.nexus.port.ui }}
          initialDelaySeconds: 120
          periodSeconds: 20
          failureThreshold: 15
          successThreshold: 1

      volumes:
        - name: molgenis-nexus-nfs
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.claim }}

    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}