apiVersion: v1
kind: ConfigMap
metadata:
  name: scrape-config-configmap
data:
  {{- if eq .Values.environment.cluster "production"}}
  - job_name: 'masterBranchNodes'
    file_sd_configs:
      - files:
        - /etc/configProm/masterTargetsAcquired.yml
  - job_name: '20BranchNodes'
    file_sd_configs:
      - files:
        - /etc/configProm/20TargetsAcquired.yml
  - job_name: '10BranchNodes'
    file_sd_configs:
      - files:
        - /etc/configProm/10TargetsAcquired.yml
  - job_name: '01BranchNodes'
    file_sd_configs:
      - files:
        - /etc/configProm/01TargetsAcquired.yml
  {{- end}}
  {{- if eq .Values.environment.cluster "development"}}
  - job_name: jenkins
    metrics_path: '/prometheus/'
    scheme: https
    static_configs:
      - targets: ['jenkins.dev.molgenis.org:443']
  {{- end}}