apiVersion: v1
kind: ConfigMap
metadata:
  name: targets-configmap
data:
  masterTargetsAcquired.yml: |
    #job
  20TargetsAcquired.yml: |
    #job
  10TargetsAcquired.yml: |
    #job
  01TargetsAcquired.yml: |
    #job