# Default values for opencpu.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

environment: production

cleanup:
  image:
    tag: v2.2.0
    repository: rancher
    name: cli2
  project: edge-molgenis
    