apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-config
  labels:
    app: {{ template "frontend.name" . }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
data:
  custom.conf: |
    {{ range $index, $location := .Values.proxy.frontend.custom -}}
    location /{{ $location.path }}/ {
      proxy_pass {{ $location.url }}/;
      {{- if and (index $location.unpkg) $location.unpkg }}
      proxy_intercept_errors on;
      recursive_error_pages on;
      error_page 301 302 307 = @handle_redirect;
      {{- end -}}
    }
    {{ end }}
  experimental.conf: |
    {{ range $index, $location := .Values.proxy.frontend.experimental -}}
    location /{{ $location.path }}/ {
      proxy_pass {{ $location.url }}/;
      {{- if and (index $location.unpkg) $location.unpkg }}
      proxy_intercept_errors on;
      recursive_error_pages on;
      error_page 301 302 307 = @handle_redirect;
      {{- end -}}
    }
    {{ end }}
  ui.conf: |
    location /@molgenis-ui/ {
      proxy_pass https://unpkg.com/@molgenis-ui/;
      proxy_intercept_errors on;
      recursive_error_pages on;
      error_page 301 302 307 = @handle_redirect;
    }
  common.conf: |
    #
    # We use this configuration in all configuration that is using unpkg.com
    # All the redirects done by unpkg.com are handled here. 
    # unpkg.com redirects 2 or 3 times depending on the url you initially post
    #
    location @handle_redirect {
      # drop routing information from urls that do not start with `/dist/`
      rewrite ^/([^/]*)/([^/]*)/(?!dist/).*$ /$1/$2 last;

      proxy_intercept_errors on;
      error_page 301 302 307 = @handle_redirect;
      set $frontend_host 'https://unpkg.com';
      set $saved_redirect_location '$upstream_http_location';
      proxy_pass $frontend_host$saved_redirect_location;
      # Do not cache these redirects too long
      expires 10m;
    }