apiVersion: v1
appVersion: "1.0"
description: MOLGENIS - helm stack (in BETA)
name: molgenis
version: 0.5.4
sources:
- https://github.com/molgenis/molgenis-ops-docker-helm.git
icon: https://raw.githubusercontent.com/molgenis/molgenis-ops-docker-helm/master/charts/molgenis/catalogIcon-molgenis.svg
home: http://molgenis.org
maintainers:
- name: sidohaakma
- name: fdlk
